# Network Configurations
quarkus.http.port=8083

kafka.bootstrap.servers=localhost:9092

# Coinbase Channel
mp.messaging.incoming.coinbase-adapter-in.connector=smallrye-kafka
mp.messaging.incoming.coinbase-adapter-in.topic=coinbase-raw-events
mp.messaging.incoming.coinbase-adapter-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.coinbase-adapter-in.group.id=data-normalizer-group

# Kraken Channel
mp.messaging.incoming.kraken-adapter-in.connector=smallrye-kafka
mp.messaging.incoming.kraken-adapter-in.topic=kraken-raw-events
mp.messaging.incoming.kraken-adapter-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kraken-adapter-in.group.id=data-normalizer-group