# Network Configurations
quarkus.http.port=8083
kafka.bootstrap.servers=localhost:9092

# Coinbase Channel
mp.messaging.incoming.coinbase-adapter-in.connector=smallrye-kafka
mp.messaging.incoming.coinbase-adapter-in.topic=coinbase-raw-events
mp.messaging.incoming.coinbase-adapter-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.coinbase-adapter-in.group.id=data-normalizer-group

# Kraken Channel
mp.messaging.incoming.kraken-adapter-in.connector=smallrye-kafka
mp.messaging.incoming.kraken-adapter-in.topic=kraken-raw-events
mp.messaging.incoming.kraken-adapter-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kraken-adapter-in.group.id=data-normalizer-group

# =====================================================================
# ? DEFAULT PROFILE (PostgreSQL via Docker Dev Services for Dev/Prod)
# =====================================================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.port=53574
quarkus.datasource.devservices.volumes."/var/lib/postgresql/data"=/C/Quarkus/postgres-data

# Stop Hibernate from modifying tables?let Liquibase create them!
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.packages=com.example.coinbase.entity,com.example.normalizer.entity

# Liquibase Configuration for running migrations on application boot
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changeLog.yaml

# =====================================================================
# ? TEST PROFILE (Automated H2 for Unit Tests)
# =====================================================================
# The %test prefix ensures these values only apply during './gradlew test'
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1

# Allow Hibernate to instantly manage the mock structure during tests
%test.quarkus.hibernate-orm.database.generation=drop-and-create

# Deactivate Liquibase migrations on tests to keep test runs fast
%test.quarkus.liquibase.migrate-at-start=false
